repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          args: ["--unsafe"]
        - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: '24.10.0'
      hooks:
        - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 7.1.1
      hooks:
        - id: flake8
          additional_dependencies:
            - flake8-bugbear
            - flake8-comprehensions
            - flake8-simplify
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.13.0'
      hooks:
        - id: mypy
          args: [--check-untyped-defs]
          additional_dependencies:
            - graphviz >= 0.20.1
            - ruamel-yaml >= 0.18.6
            - rich >= 13.7.0
            - numpy >= 1.24
            - hypothesis >= 6.99.6
            - xarray >= 2023.1
    - repo: https://github.com/pycqa/isort
      rev: '5.13.2'
      hooks:
        - id: isort
