[tool.poetry]
name = "phileas"
version = "0.2.0"
description = ""
authors = ["Louis Dubois <louis.dubois@ssi.gouv.fr>"]
readme = "Readme.md"

[tool.poetry.dependencies]
python = "^3.8"
graphviz = "^0.20.1"
rich = "^13.7.0"
ruamel-yaml = "^0.18.6"
numpy = "^1.24"


[tool.poetry.group.dev.dependencies]
ipython = "^7"
ipdb = "^0.13.13"
pre-commit = "3.5"
hypothesis = "^6.99.6"

[tool.poetry.scripts]
phileas = 'phileas.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
