[tool.poetry]
name = "phileas"
version = "0.1.0"
description = ""
authors = ["Louis Dubois <louis.dubois@ssi.gouv.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
