[tool.poetry]
name = "phileas"
version = "0.4"
description = ""
authors = ["Louis Dubois <louis.dubois@ssi.gouv.fr>"]
readme = "Readme.md"

[tool.poetry.dependencies]
python = "^3.8"
graphviz = "^0.20.1"
rich = "^13.7.0"
ruamel-yaml = "^0.18.6"
numpy = "^1.24"
jinja2 = "^3.1.4"

[tool.poetry.group.dev.dependencies]
ipython = "^7"
ipdb = "^0.13.13"
pre-commit = "3.5"
hypothesis = "^6.99.6"
coverage = {version = ">=7.6", extras = ["toml"]}
mypy = "^1.13.0"
xarray = ">=2023.1"

[tool.poetry.scripts]
phileas = 'phileas.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true
omit = [
    "./test/",
    "./tox",
]

[tool.coverage.report]
exclude_also = [
    "pragma: no cover",
    "raise NotImplementedError()",
]
